[model]
model = "gpt-4o-mini"
enable_multi_modal = false
ollama_server_url = "http://localhost:11434"

[sample_prompts]
prompts = [
  "Analyze lyrics",
  "Analyze this song's style and instruments",
  "Based on the lyrics, analyze the song style, list possible song styles, and provide a description of the song's instrument structure",
  "Given a song's lyrics, analyze the song's style, list possible styles, and provide a description of the song's instrument structure",
  "Given a song's lyrics, analyze the song's style, list possible styles, provide a description of the song's instrument structure, and generate a song title",
  "Given a song's lyrics, analyze the song's style, list possible styles, provide a description of the song's instrument structure, and generate a song style",
  "Given a song's lyrics, analyze the song's style, list possible styles, provide a description of the song's instrument structure, and generate a song title and style",
  "Given a song's lyrics, analyze the song's style, list possible styles, provide a description of the song's instrument structure, and generate lyrics",
  "Given a song's lyrics, analyze the song's style, list possible styles, provide a description of the song's instrument structure, and generate a song",
  "Generate a song based on your idea",
  "Generate Suno song",
  "Call Suno API to generate song",
]

[environment]
type = "dev"

[timeout]
llm = 30

# example of agent in a swarm
[target_agent_id]
model = "claude-3-5-sonnet-20240620"
#model = "gpt-3.5-turbo"
timeout = 15
environment = "dev"
enable_multi_modal = true
ollama_server_url = 'http://123.456.78.90:11434'
sample_prompts = [
  "What can you help me do?",
  "Which tools do you have access to?",
  "What are your capabilities?",
]
